### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by marcomusy** [banesullivan/gendocs#1]
Hi, I'm getting this error message when trying to use the package, maybe i'm doing something wrong.. i'm very new to sphinx.

![image](https://user-images.githubusercontent.com/32848391/50832010-18250680-134d-11e9-9db4-d5ec4caa2a44.png)

thanks a lot, best regards

**Comment by banesullivan** [comment]
Hmm... I suspect you don't have the `__all__` specified for every module. Right now, `gendocs` operates on the assumption that `__all__` is specified to ensure external libraries/modules like `sys` are not documented. 

I suppose I need to make a more robust way of ignoring external libraries... in the meantime, do you have the code pushed to a branch on [`vtkplotter`](https://github.com/marcomusy/vtkplotter)? I'd be happy to check it out help!

**Comment by marcomusy** [comment]
..indeed i didn't specify `__all__` anywhere in the module.
if you want to make tests with the code i don't have any local changes to commit.
thanks for the quick reply and for the help!

**Comment by banesullivan** [comment]
[As detailed in the docs](https://gendocs.readthedocs.io/en/latest/content/gendocs/generator.html), an `__all__` is necessary for every module in your package in order for `gendocs` to know what parts of the package are available and should be documented.

I had some extra time and thought I'd set up the infrastructure for you: https://github.com/marcomusy/vtkplotter/pull/8

**Comment by marcomusy** [comment]
thanks again, so helpful!
